FROM node:23-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source files
COPY . .

EXPOSE 5173

# Run dev server (for development)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]