sync:
    rsync -avhzL --delete \
				--no-perms --no-owner --no-group \
				--exclude .git \
				--exclude node_modules \
				--exclude docker \
				--exclude dist \
				./ root@103.20.144.71:/root/tmp