#!/bin/bash

# Database Seeding Quick Commands
# Run from backend directory

echo "🌱 Database Seeding Commands"
echo "================================"
echo ""
echo "Available commands:"
echo ""
echo "1. npm run seed"
echo "   → Seed data (skips if exists)"
echo ""
echo "2. npm run seed:reset"
echo "   → Clear ALL data and re-seed fresh"
echo ""
echo "3. npm run db:reset"
echo "   → Clear ALL data only (no re-seeding)"
echo ""
echo "================================"
echo ""
echo "📊 What gets seeded:"
echo "   • 4 Architecture types"
echo "   • 5 Users (admin + developers + viewer)"
echo "   • 3-5 API tokens"
echo "   • 8 Projects"
echo "   • 172 Pipeline runs (30 days history)"
echo "   • 10 Analysis reports"
echo ""
echo "🔐 Default credentials:"
echo "   Email: admin@example.com"
echo "   Password: password123"
echo ""
echo "================================"
